# Dependabot Konfiguration f체r SC-Griefing-Counter
version: 2
updates:
  # Updates f체r pip (Python-Pakete)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    # Gruppierung 채hnlicher Updates
    groups:
      python-packages:
        patterns:
          - "*"
        exclude-patterns:
          - "nuitka"
          - "pyarmor"
    # Ignoriere bestimmte Updates (bei Bedarf anpassen)
    ignore:
      # Beispiel: Major-Updates von watchdog ignorieren
      - dependency-name: "watchdog"
        update-types: ["version-update:semver-major"]

  # Updates f체r GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3