"""Initial migration

Revision ID: 9d824003a350
Revises: 
Create Date: 2025-05-08 18:54:52.645620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d824003a350'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_positions',
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('last_offset', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('file_path')
    )
    op.create_table('kills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('killed_player', sa.String(), nullable=True),
    sa.Column('killer', sa.String(), nullable=True),
    sa.Column('zone', sa.String(), nullable=True),
    sa.Column('weapon', sa.String(), nullable=True),
    sa.Column('damage_class', sa.String(), nullable=True),
    sa.Column('damage_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timestamp', 'killed_player', 'killer', 'zone', 'weapon', 'damage_class', 'damage_type', name='uix_kill_event')
    )
    op.create_table('migrations',
    sa.Column('version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('npc_categories',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('npc_categories')
    op.drop_table('migrations')
    op.drop_table('kills')
    op.drop_table('file_positions')
    # ### end Alembic commands ###
